version: "3.9"
services:
  website-prod:
    build:
      context: ./
      dockerfile: Dockerfile.prod
      args:
        - VITE_APP_BACKEND_ADDRESS=https://localhost/api/prod
    container_name: bond-ui-prod
    restart: always
    ports:
      - 3000:3000
    networks:
      - network
networks:
  network:
